# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'To-Do List' do

pod 'MagicalRecord'
pod 'LGPlusButtonsView', '~> 1.0.0'
pod 'LGActionSheet', '~> 1.0.0'


end

